apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: contoso-website
  namespace: {{ default "test" .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: contoso-{{ default "test" .Release.Namespace }}.{{ .Values.dns.name }}
      http:
        paths:
          - backend:
              serviceName: contoso-website
              servicePort: http
            path: /
